### ISSUE TITLE
Database의 password_check 란 칼럼은 필요한 것인가

### ISSUE THREAD

**Issue by dnrgus4659** [dnrgus4659/HOSEO-2A-1-DamoaTaxi#8]
password_check 부분을 회원가입 시에 입력하지만 javascript로 유효성 검사만 하면 되는 것 같은데 db에 저장하는건 맞는 일인지 자료조사를 통해 알아보기!

**Comment by Jachmo** [comment]
Javascript로 유효성 검사를 하게 되면, 기능상으론 문제는 없습니다.

하지만, 개발자 도구를 통해 값 변조를 통해 회피가 가능합니다.

그리하여 변조된 값을 서버에 요청하게 되어서 데이터를 얼마든지 변조가 가능합니다. 

그래서 제 생각에는 JSP단에서 검증을 같이 하는게 좋다고 생각하여 필요하다고 생각은 합니다.

참고한 블로그는 https://jojoldu.tistory.com/157 입니다.
